### ISSUE TITLE
When (day and time) will we discuss the next conference's place

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aoscc#10]

**Comment by MingcongBai** [comment]
Day 1, afternoon.

`3:30 P.M.  Mingcong Bai: polls and discussions about the coming year`

"During Day 1, reports and reflections will contain reviews of community involvement, project achievements, and stuff that are more or less left behind (and therefore should be taken care of in short order).

Planning and discussions are two other important component of Day 1, which will consist of:
- Discussions: some features or new stuff are worth discussing over before the real "do", so we will do that here.
- Votes/Polls:
  -  Codename of next year's AOSC OS development.
  -  Next year's default wallpaper for AOSC OS.
  -  Next year's AOSCC location."
