### ISSUE TITLE
AOSC OS Core 8 Development Codename Nomination

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aoscc#14]
Post your codename nomination below! Nomination will close on July 8 at 23:59 (UTC +8 time), nominator to winning codename next week will be awarded with a special gift.

Do's for Nominations
--------------------------------

- Codenames should start with letter "H".
- Make it fun, make it memorable.

Do Not's for Nominations
-------------------------------------

- No political topic, implications, or commentary.
- No sexual expression or implication.
- No profanity.
- No trademarks.

To Nominate
-------------------

Just post your nomination below!

**Comment by NeoChen1024** [comment]
HONK

**Comment by Hexhu** [comment]
~HSO~

**Comment by dragonJACson** [comment]
Hardbass

**Comment by MarvelousBlack** [comment]
~Hui（Human User Interface）~

**Comment by Hexhu** [comment]
Hui

**Comment by NeoChen1024** [comment]
Hexdecimal

**Comment by misaka00251** [comment]
Hitokoto

**Comment by thxo** [comment]
> HONK

Hjönk

**Comment by StephDC** [comment]
Hmm

**Comment by OriginCode** [comment]
Hex

**Comment by CamberLoid** [comment]
Helium

From Wikipedia:
Helium (from Greek: ἥλιος, romanized: Helios, lit. 'Sun') is a chemical element with the symbol He and atomic number 2.
~~Short. Memorable. Cool.~~

Hydrogen is OK but i think it is less memorable, so I just passed it.

**Comment by MarvelousBlack** [comment]
Hong

**Comment by NeoChen1024** [comment]
Hive

**Comment by hosiet** [comment]
Hakase

**Comment by KireinaHoro** [comment]
Hestia.

> HESTIA Ἑστία f Greek Mythology
> Derived from Greek ἑστία (hestia) meaning "hearth, fireside". In Greek mythology Hestia was the goddess of the hearth and domestic activity.

Not aware of any conflicts except a [WordPress theme](https://ja.wordpress.org/themes/hestia/).

**Comment by MarvelousBlack** [comment]
hero

**Comment by LionNatsu** [comment]
~Homo~

**Comment by RedL0tus** [comment]
`Honorificabilitudinitatibus`

> The state of being able to achieve honours
> Longest word in Shakespeare's works; longest word in the English language featuring alternating consonants and vowels.

(From Wikipedia)

**Comment by chenx97** [comment]
heap

**Comment by liushuyu** [comment]
Helix

**Comment by MarvelousBlack** [comment]
Hongmeng

**Comment by eatradish** [comment]
hhhhh
haha
hehe

**Comment by NeoChen1024** [comment]
Homophonic

**Comment by LionNatsu** [comment]
Homomorphism

> Many mathematics, Very algebra

**Comment by MingcongBai** [comment]
Halva

**Comment by eatradish** [comment]
holy*

**Comment by ctlee61** [comment]
Hyperthermia (

**Comment by LionNatsu** [comment]
Haru

> My cat's name

**Comment by Hexhu** [comment]
Huh

**Comment by yangfl** [comment]
Hypercube

**Comment by hosiet** [comment]
[Halifax](https://en.wikipedia.org/wiki/Halifax)

> Name for several cities

**Comment by szclsya** [comment]
Homogeneity

**Comment by NeoChen1024** [comment]
Hellschreiber

**Comment by MarvelousBlack** [comment]
ひめ（hime）

**Comment by eatradish** [comment]
hakumei

**Comment by yangfl** [comment]
~Helvetica~

**Comment by NeoChen1024** [comment]
> Hellschreiber

The Hellschreiber, Feldhellschreiber or Typenbildfeldfernschreiber (also Hell-Schreiber named after its inventor Rudolf Hell) is a facsimile-based teleprinter invented by Rudolf Hell. 

(from Wikipedia)

**Comment by eatradish** [comment]
hydia

**Comment by RedL0tus** [comment]
Hyperjellyemia

Hyper- means high
jelly means jelly
-emia means presence in blood

High jelly presence in blood.

**Comment by szclsya** [comment]
Hyrule

**Comment by CamberLoid** [comment]
Hoshiguma

An operator's codename of Arknights. Not a trademark

**Comment by MarvelousBlack** [comment]
hostnamectl

**Comment by yangfl** [comment]
Hell

**Comment by LionNatsu** [comment]
Hotfix

> DO NOT USE THIS

**Comment by M0gician** [comment]
Hypnos

> (Greek mythology) the Greek god of sleep

**Comment by LionNatsu** [comment]
Hayaku

> 小平点评：“就感觉到快，有催人跑的意思”

**Comment by 67au** [comment]
Hijack

**Comment by szclsya** [comment]
Hax

**Comment by StephDC** [comment]
Holy ****

**Comment by StephDC** [comment]
HelloWorld

**Comment by RedL0tus** [comment]
HiDPI

> Pretty obvious

**Comment by StephDC** [comment]
~HiRes~

**Comment by MingcongBai** [comment]
Hi-Fi

**Comment by szclsya** [comment]
Harpsichord

**Comment by MarvelousBlack** [comment]
Hoopa

**Comment by nonabyte** [comment]
Henshin (変身)

**Comment by StephDC** [comment]
HeT

> OCR

**Comment by simonsmh** [comment]
~Hololive~

**Comment by MarvelousBlack** [comment]
saltedfish
hsifdetlas

**Comment by Icenowy** [comment]
Homlet

**Comment by yangfl** [comment]
Hashtable

**Comment by MingcongBai** [comment]
Hitori

**Comment by liushuyu** [comment]
Hashbrown

**Comment by simonsmh** [comment]
~Helltaker~

**Comment by MingcongBai** [comment]
ℌ𝔢𝔩𝔩'𝔰 𝔗𝔞𝔠𝔬

> https://www.reddit.com/r/Wellthatsucks/comments/c9f9rc/sewer_explosion/esxoji1/

**Comment by StephDC** [comment]
HTML_is_a_programming_language

**Comment by nonabyte** [comment]
Hoshi（星）

**Comment by MingcongBai** [comment]
Higher on the Street

**Comment by StephDC** [comment]
~Ha~

> 真正的粉絲⋯⋯

**Comment by RedL0tus** [comment]
HeyHeyHeyStartDash

**Comment by MarvelousBlack** [comment]
haway

/'ha wa/ Used by 'mackems' or people originating from the Sunderland area (North East England), similar meaning and use to the geordie 'howay'. Meaning 'come on' can be used either in the sense of travelling somewhere, or more commonly used at football matches as an expression to get your team to perform harder.

**Comment by OriginCode** [comment]
~~Hoshimati~~
Hoshimachi
~~Hosimati~~
~~Hosimachi~~
~（星街）ref to a VTuber. 🙈~

**Comment by Suyun514** [comment]
Hso

**Comment by chenx97** [comment]
> Hoshimati
> Hoshimachi
> Hosimati
> Hosimachi
> （星街）ref to a VTuber. see_no_evil

Please pick one of these romanized results.

**Comment by imi415** [comment]
Hanabi
Japanese word '花火' (fireworks)

**Comment by MarvelousBlack** [comment]
homectl

**Comment by Suyun514** [comment]
~Hamachi~

**Comment by OriginCode** [comment]
Haachama

**Comment by StephDC** [comment]
~Hass~

> A species of avocado, don't think too much

**Comment by MarvelousBlack** [comment]
highlight（

**Comment by LionNatsu** [comment]
Hall effect

> Magnetic force on moving charged matters.

**Comment by MarvelousBlack** [comment]
halt

**Comment by Harry-Chen** [comment]
Hybrid

**Comment by outloudvi** [comment]
Hey

**Comment by MarvelousBlack** [comment]
help

**Comment by chenx97** [comment]
hanafuda

**Comment by MingcongBai** [comment]
Harry Chen

**Comment by outloudvi** [comment]
Houdini

**Comment by StephDC** [comment]
~How_dare_you~

>蠔爹油

**Comment by szclsya** [comment]
Hotpot

**Comment by NeoChen1024** [comment]
Honeypot

**Comment by LionNatsu** [comment]
~Heise Gaoji Jiaoche~

> Chinese name of the car owned by a driving licence check man who enjoys dog's barking.

**Comment by MingcongBai** [comment]
Hoisin Sauce

**Comment by chenx97** [comment]
Heisei
> 平成

**Comment by 67au** [comment]
Hea

> Hea来自粤语，常用意思是“漫无目的地消耗时间”，而古粤语的是探索、寻找，其含义是想“发现”些什么，但是有不知道有什么可以被“发现”，所以一定要去“探索”一下。

> 疫情期间“留係屋企Hea住”开发的版本，叫AOSC OS Hea 也很合理

**Comment by bobcao3** [comment]
Howdy

**Comment by XYenon** [comment]
hammer

**Comment by MarvelousBlack** [comment]
Hall king 好勁

**Comment by MarvelousBlack** [comment]
Haveged

**Comment by XYenon** [comment]
HayasakaAi

**Comment by MarvelousBlack** [comment]
high-speed


new high-speed AOSC number 114514 using ehci-pci

**Comment by Yangff** [comment]
hue

**Comment by Hexhu** [comment]
~How Die You~
~蚝爹油~

**Comment by axionl** [comment]
Homogeneous

**Comment by CattenLinger** [comment]
Hercules

**Comment by neruthes** [comment]
~Hui~

**Comment by neruthes** [comment]
Himalayas

**Comment by RedL0tus** [comment]
(HotSpot)

> AOSC OS 8u192 (HotSpot)

**Comment by Plectranthus-fg** [comment]
husky（

**Comment by Konano** [comment]
Harry

**Comment by kLiHz** [comment]
hallelujah (

**Comment by SuperMarioSF** [comment]
~HiRes~

> maybe LoRes also a good one (

**Comment by SuperMarioSF** [comment]
HardDiskDrive
aka. HDD

> Why HDD? Because AOSC codename have been skipped initial A and initial B, just like the PC, which skipped drive letter A and B which reserved for floppy disk drives and start from C for a hard disk drive.

**Comment by SuperMarioSF** [comment]
HID

> Ah, USB HID, all kinds of strange input devices, all talk with HID protocol.
> To boost your keyboard input speed, try to use a USB 3.0 keyboard (x

**Comment by SuperMarioSF** [comment]
HideAndSeek

> 年度捉迷藏冠军：分号

**Comment by SuperMarioSF** [comment]
Hmmm

> r/hmmm

**Comment by Hexhu** [comment]
Hu-Fi

> Hi-Fi 的反义词

**Comment by MingcongBai** [comment]
Invalid nominations will be removed prior to voting this week. Please note that the codenames listed below, although may not actually violate any rules specified, could still be interpreted as such by any given individual - apologies in advance.

Currently Invalidated
=================

Sexual Implications
-----------------------------

- @Hexhu: HSO
- @MarvelousBlack: Hui
- @LionNatsu: Homo, Heise Gaoji Jiaoche
- @neruthes: Hui

Political Implications
------------------------------

- @StephDC: Ha, How_dare_you, Hass
- @Hexhu: How Die You

Potential Trademarks
-------------------------------

Most of the codenames listed below are names of VTubers or games, which are potential subject to Trademark Laws in each of their respective jurisdictions or markets.

- @simonsmh: Hololive, Helltaker
~@OriginCode: Hoshimachi, Haachama~
- @Suyun514: Hamachi

**Comment by neruthes** [comment]
Hippogryph

**Comment by NeoChen1024** [comment]
Hook-off

**Comment by MingcongBai** [comment]
Invalid nominations will be removed prior to voting this week. Please note that the codenames listed below, although may not actually violate any rules specified, could still be interpreted as such by any given individual - apologies in advance.

Currently Invalidated
=================

Sexual Implications
-----------------------------

- @Hexhu: HSO
- @MarvelousBlack: Hui
- @LionNatsu: Homo, Heise Gaoji Jiaoche
- @neruthes: Hui

Political Implications
------------------------------

- @StephDC: Ha, How_dare_you, Hass
- @Hexhu: How Die You

Potential Trademarks
-------------------------------

Most of the codenames listed below are names of VTubers or games, which are potential subject to Trademark Laws in each of their respective jurisdictions or markets.

- @simonsmh: Hololive, Helltaker
- @Suyun514: Hamachi
- @SuperMarioSF: HiRes

**Comment by Icenowy** [comment]
Hooked Dragonite
`a famous glitch in Gen I Pokemon games`

**Comment by SuperMarioSF** [comment]
HotGarbageMaker

> aka. Super Mario Maker awful maps...
> will be shocked if this name being selected...

**Comment by KexyBiscuit** [comment]
Heterogeneous

> [Intel® Core™ Processors with Intel® Hybrid Technology](https://ark.intel.com/content/www/us/en/ark/products/series/202779/intel-core-processors-with-intel-hybrid-technology.html)

**Comment by bobcao3** [comment]
Height
-> Try to pronounce it in French, like OS Core (h)Eight

**Comment by neruthes** [comment]
Hexhu

**Comment by MingcongBai** [comment]
Also disqualifying "Helvetica" from @yangfl as this is a trademark.

**Comment by MingcongBai** [comment]
Attention, our first round of polls will start in about 20 minutes, please head to our [polling channel](https://t.me/core8poll) now!

各位请注意，我们的第一轮投票将在约 20 分钟后开始，请前往我们的 [投票频道](https://t.me/core8poll) 参与投票！
