### ISSUE TITLE
Road to the Conference

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aoscc#4]
Here is a simple roadmap to the conference, of stuff we need to get done:
- [ ] Material collection;
  - [ ] Sticker packs materials;
  - [ ] Possible conference locations;
- [ ] Communications;
  - [ ] With the locations;
  - [ ] Sticker pack production;
- [ ] Propaganda! Time to let people know (hopefully before July);

**Comment by jyhi** [comment]
We can contact Connext guys to get a place.

**Comment by bobcao3** [comment]
Our school can provide a place

**Comment by jyhi** [comment]
![image](https://cloud.githubusercontent.com/assets/4285573/14558976/462afaa8-0338-11e6-89de-4d1c41deadea.png)

**Comment by m13253** [comment]
Connext 一个地铁都不通的地方，不。去。

**Comment by bobcao3** [comment]
I suggest to have this conference before 7/13. Someone (or ones) have summer program after 7/13.

**Comment by jyhi** [comment]
> I suggest to have this conference before 7/13. Someone (or ones) have summer program after 7/13.

Oh I just don't want to rush between Connext and AOSCC actually...

**Comment by Yexiaoxing** [comment]
re-tag: aoscc-2017

**Comment by MingcongBai** [comment]
Might as well open another issue. Closing...
