### ISSUE TITLE
When will the first day's agenda start?

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aoscc#9]
Require details for reserving tickets.

**Comment by LionNatsu** [comment]
Oops, I found it. 10 a.m.

**Comment by MingcongBai** [comment]
@LionNatsu The first day starts at noon for most might need to ride a train or plane there. Could you close this issue since it's quite fine and clear for you?

**Comment by LionNatsu** [comment]
@MingcongBai Is it not finally decided yet?
Well, I'd like to come here(SHA) by train, but the best line is Z100 which may arrive at 10:37 a.m..

**Comment by MingcongBai** [comment]
> Well, I'd like to come here(SHA) by train, but the best line is Z100 which may arrive at 10:37 a.m..

As I said, the first day actually starts at noon, that is 12:00. So you are good on that part. All other days will start at 10:00.

> Is it not finally decided yet?

Well the time at which the conference start on each day is, but detailed scheduling is not available just yet (pushing for July 1st at this point).

**Comment by LionNatsu** [comment]
Oh yes. It's so clear and good for me/us.

**Comment by MingcongBai** [comment]
> Oh yes. It's so clear and good for me/us.

Do have fun on the way though!
